spring.application.name=transportadora

spring.datasource.url=jdbc:postgresql://localhost:5432/transportadora_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.data.web.pageable.default-page-size=10
spring.mvc.pathmatch.use-suffix-pattern=false

storage.local.path=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=ortizlog-secret-key-2024-transportadora-sistema
jwt.expiration=36000000

transportadora.latitude=-23.297558326554533
transportadora.longitude=-47.30306815860599

server.port=8080
